version: "3.8"

services:
  database:
    image: mongo
    container_name: database
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=challenge
    volumes:
      - mongodata:/data/mongo
    ports:
      - 27017:27017

  app:
    build: .
    container_name: challenge-backend
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
    links:
      - database
    depends_on:
      - database

volumes:
  mongodata:
    driver: local
